apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
      - name: generate-log
        image: chrisme96/dwk-generate-log:1.10
        volumeMounts:
          - name: shared-logs
            mountPath: /app/logs
      - name: read-log
        image: chrisme96/dwk-read-log:1.10
        volumeMounts:
          - name: shared-logs
            mountPath: /app/logs