apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  labels:
    app: ping-pong
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ping-pong