apiVersion: v1
kind: Service
metadata:
  name: the-project-svc
  labels:
    app: the-project
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: the-project